INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('negroni','Negroni','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('milk','Milk','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('olive','Olive','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('strawberry','Strawberry','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('jam','Jam','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('cornichon','Cornichon','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('macaroni','Macaroni','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('bird-s-eye-chili','Bird''s Eye Chili','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('clementine','Clementine','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('tinned-fish','Tinned Fish','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('cheese-1','Cheese #1','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('cheese-2','Cheese #2','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('goldfish','Goldfish','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('cheez-it','Cheez-It','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('you-me-conversation-heart','You & Me Conversation Heart','mini',0,6,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('mystery-pack','Mystery Pack','pack',0,18,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('metrocard','MetroCard','big-riso',0,20,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('evening-on-the-b-train','Evening on the B Train','big-riso',0,20,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('on-the-road','On The Road','big-riso',0,20,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('jello','Jello','big-riso',0,20,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('rainbow-swiss-chard','Rainbow Swiss Chard','big-riso',0,20,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('grand-central-terminal-ceiling','Grand Central Terminal Ceiling','big-riso',0,22,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('grand-central-terminal-clock','Grand Central Terminal Clock','big-riso',0,22,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('rainbow-cookie','Rainbow Cookie','linocut',0,15,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('mini-pbr-can','Mini PBR Can','linocut',0,15,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('camp-coffee','Camp Coffee','linocut',0,15,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('hot-dog','Hot Dog','linocut',0,15,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('cento-tomato-can','Cento Tomato Can','linocut',0,15,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('garlic-scapes','Garlic Scapes','linocut',0,15,'in-print');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('grand-central','Grand Central','exclusive',1,NULL,'unknown');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('holiday-edition','Holiday Edition','exclusive',1,NULL,'unknown');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('monet-s-flowers','Monet''s Flowers','exclusive',1,NULL,'unknown');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('pipe','Pipe','exclusive',1,NULL,'unknown');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('lamp-post','Lamp Post','exclusive',1,NULL,'unknown');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('lowly-worm','Lowly Worm','exclusive',1,NULL,'unknown');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('pickle-car','Pickle Car','exclusive',1,NULL,'unknown');
INSERT OR IGNORE INTO catalog (print_id,title,series,exclusive,retail,status) VALUES ('lacma-set','LACMA set','pack',1,NULL,'unknown');
