/* QR Forge · source/qr-gf.js
   GF(256) arithmetic and Reed-Solomon, per ISO/IEC 18004.
   Field is generated by x^8 + x^4 + x^3 + x^2 + 1 (0x11D). No dependencies. */
(function (root) {
  'use strict';

  /* Carry-less multiply with reduction folded into the loop. Table-free on
     purpose: the whole file stays auditable and there is no init step. */
  function mul(x, y) {
    var z = 0;
    for (var i = 7; i >= 0; i--) {
      z = (z << 1) ^ ((z >>> 7) * 0x11D);
      z ^= ((y >>> i) & 1) * x;
    }
    return z & 0xFF;
  }

  /* Coefficients of the generator polynomial for `degree` ECC codewords:
     the product of (x - a^i) for i in 0..degree-1, highest power first, with
     the implicit leading 1 left off. */
  function divisor(degree) {
    var r = new Uint8Array(degree);
    r[degree - 1] = 1;
    var root = 1;
    for (var i = 0; i < degree; i++) {
      for (var j = 0; j < degree; j++) {
        r[j] = mul(r[j], root);
        if (j + 1 < degree) r[j] ^= r[j + 1];
      }
      root = mul(root, 2);
    }
    return r;
  }

  /* Polynomial long division, remainder only. The remainder IS the ECC block. */
  function remainder(data, div) {
    var r = new Uint8Array(div.length);
    for (var i = 0; i < data.length; i++) {
      var factor = data[i] ^ r[0];
      r.copyWithin(0, 1);
      r[r.length - 1] = 0;
      for (var j = 0; j < div.length; j++) r[j] ^= mul(div[j], factor);
    }
    return r;
  }

  root.QRGF = { mul: mul, divisor: divisor, remainder: remainder };
})(window);
