/* panel.js — race brief + season brief side panels, event wiring, boot.
   Loaded last; calls load() from data.js. Uses render() from matrix.js. */
function teamChip(t){return `<span class="panel-team"><span class="team-bar" style="--team:${teamColor(t)}"></span>${t}</span>`;}
function tyreChips(arr){return arr?`<div class="tyres">`+arr.map((c,i)=>`${i>0?'<span class="tyre-arrow">\u203A</span>':''}<span class="tyre ${c}">${c}</span>`).join('')+`</div>`:'';}

function raceBrief(roundNo,id){
  const rd=ROUNDS.find(x=>x.round==roundNo);const m=cellMeta(rd,id);const det=m.det||{};const finish=m.status==='DNF'?'DNF':m.pos;det.finish=finish;
  const name=DRV[id].name,team=DRV[id].team;const isFL=rd.fastestLap&&rd.fastestLap.driverId===id,isPole=rd.pole&&rd.pole.driverId===id;
  const sp=rd.sprint?rd.sprint.classification.find(x=>x.driverId===id):null;const total=(sp?sp.points:0)+m.pts;
  let badges='';if(isPole)badges+=`<span class="badge">Pole</span>`;if(isFL)badges+=`<span class="badge fl">Fastest Lap</span>`;if(sp)badges+=`<span class="badge spr">Sprint P${sp.pos} \u00B7 +${sp.points}</span>`;
  let flow;if(det.grid){const gd=m.gridDelta,dcls=gd>0?'up':(gd<0?'down':''),dtxt=gd>0?`\u25B2 +${gd}`:(gd<0?`\u25BC ${gd}`:'\u2013 held');flow=`<div class="flow"><div class="node"><span class="nl">Grid</span><span class="nv num">${det.grid}</span></div><div class="arrow"><span class="delta ${dcls} num">${m.status==='DNF'?'':dtxt}</span><span class="track"></span></div><div class="node"><span class="nl">Finish</span><span class="nv ${finish===1?'win':''} ${m.status==='DNF'?'dnf':''} num">${m.status==='DNF'?'DNF':'P'+finish}</span></div></div>`;}else{flow=`<div class="flow"><div class="node"><span class="nl">Finish</span><span class="nv ${finish===1?'win':''} ${m.status==='DNF'?'dnf':''} num">${m.status==='DNF'?'DNF':'P'+finish}</span></div></div>`;}
  const noteText=m.note?m.note.text:null;const tagText=(det.story&&det.story.length)?renderStory(det.story,det):[];let storyHtml='';if(noteText||tagText.length){const isMv=!m.note&&m.bigMover;storyHtml=`<div class="story-box ${isMv?'mv':''}"><span class="sdot"></span><div class="stext">${noteText?`<p>${noteText}${m.note.onRoad?` <b>(on road: P${m.note.onRoad})</b>`:''}</p>`:''}${tagText.map(t=>`<p>${t}</p>`).join('')}</div></div>`;}
  const hasIllus=!!det.grid;const il=hasIllus?'illus':'';let stats=`<div class="stat-grid"><div class="stat"><span class="sl">Race Pts</span><span class="sv num">${m.pts}</span></div><div class="stat"><span class="sl">Sprint</span><span class="sv num">${sp?sp.points:'\u2014'}</span></div><div class="stat"><span class="sl">Total</span><span class="sv num">${total}</span></div>`;if(det.best)stats+=`<div class="stat ${il}"><span class="sl">Best Lap</span><span class="sv num">${det.best}</span></div>`;if(det.pits!=null)stats+=`<div class="stat ${il}"><span class="sl">Pits</span><span class="sv num">${det.pits}</span></div>`;if(det.tyres)stats+=`<div class="stat ${il}"><span class="sl">Tyres</span>${tyreChips(det.tyres)}</div>`;stats+=`</div>`;
  const illusNote=hasIllus?`<div class="illus-note"><b>Preview:</b> grid, lap, pits and tyres are illustrative; verified values (OpenF1) fill these once sourced.</div>`:'';
  return `<div class="panel-head" style="--team:${teamColor(team)}"><div><div class="panel-ey">R${rd.round} \u00B7 ${rd.name}${rd.sprint?' \u00B7 Sprint':''}</div><div class="panel-drv">${name}</div>${teamChip(team)}</div><button class="x" aria-label="Close">\u00D7</button></div><div class="panel-body">${flow}${badges?`<div class="badges">${badges}</div>`:''}${storyHtml}${stats}<div class="report">${rd.summary?`<p>${rd.summary}</p>`:''}</div>${illusNote}</div>`;
}

function seasonBrief(id){
  const d=STANDINGS.find(x=>x.id===id),w=wins(id),best=bestFin(id);
  const rows=ROUNDS.map(rd=>{const r=raceRow(rd,id);const sp=rd.sprint?rd.sprint.classification.find(x=>x.driverId===id):null;let fin='\u2014',pts=0;if(r){fin=r.status==='DNF'?'DNF':'P'+r.pos;pts=r.points+(sp?sp.points:0);}return `<div class="season-row"><span class="sr-rn num">R${rd.round}</span><span class="sr-ev">${codeOf(rd)} \u00B7 ${rd.name.replace(' Grand Prix','')}</span><span class="sr-fin num" style="color:${r&&r.pos===1?'var(--gold)':r&&r.status==='DNF'?'var(--red)':'var(--txt)'}">${fin}</span><span class="sr-pts num">${pts||''}</span></div>`;}).join('');
  const mate=teammate(id);let h2hHtml='';if(mate){const[me,them]=h2h(id,mate);h2hHtml=`<div class="h2h"><div><div class="h2h-l">Teammate H2H</div><div class="h2h-score"><span class="${me>=them?'win-n':'lose-n'}">${me}</span><span style="color:var(--txt-dim);font-size:0.9rem">\u2013</span><span class="${them>me?'win-n':'lose-n'}">${them}</span></div></div><div class="h2h-vs">race finishes<br>vs <b>${LAST(mate)}</b></div></div>`;}
  const tr=rankTrajectory(id);const N=tr.length;const maxR=Math.max(...tr,3);const pts=tr.map((rk,i)=>[N>1?(i/(N-1))*100:0,((rk-1)/(maxR-1))*100]);const poly=pts.map(p=>`${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(' ');const dots=pts.map((p,i)=>`<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="${i===N-1?3.5:2}" fill="${i===N-1?teamColor(d.team):'var(--txt-dim)'}"/>`).join('');const traj=`<div class="traj"><div class="tl"><span>Championship Position</span><span class="num" style="color:var(--txt-mid)">R1 \u2192 R${N}</span></div><svg viewBox="-4 -6 108 112" preserveAspectRatio="none"><polyline points="${poly}" fill="none" stroke="${teamColor(d.team)}" stroke-width="2" stroke-linejoin="round" vector-effect="non-scaling-stroke"/>${dots}</svg></div>`;
  return `<div class="panel-head" style="--team:${teamColor(d.team)}"><div><div class="panel-ey">Season \u00B7 Championship P${d.champRank}</div><div class="panel-drv">${d.name}</div>${teamChip(d.team)}</div><button class="x" aria-label="Close">\u00D7</button></div><div class="panel-body"><div class="stat-grid"><div class="stat"><span class="sl">Total</span><span class="sv num" style="color:${d.champRank===1?'var(--gold)':'var(--txt)'}">${d.total}</span></div><div class="stat"><span class="sl">Pos</span><span class="sv num">P${d.champRank}</span></div><div class="stat"><span class="sl">Race / Spr</span><span class="sv num">${d.race}<small> / ${d.sprint}</small></span></div><div class="stat"><span class="sl">Wins</span><span class="sv num">${w}</span></div><div class="stat"><span class="sl">Best</span><span class="sv num">${best===99?'\u2014':'P'+best}</span></div><div class="stat"><span class="sl">Rounds</span><span class="sv num">${ROUNDS.length}</span></div></div>${h2hHtml}${traj}<div><span class="section-h">Round by round</span><div class="season-list">${rows}</div></div></div>`;
}

const scrim=document.getElementById('scrim'),panel=document.getElementById('panel');
function openPanel(html,team){panel.style.setProperty('--team',teamColor(team));panel.innerHTML=html;panel.classList.add('open');scrim.classList.add('open');const x=panel.querySelector('.x');if(x)x.focus();}
function closePanel(){panel.classList.remove('open');scrim.classList.remove('open');}

document.addEventListener('click',e=>{
  const sortEl=e.target.closest('[data-sort]');if(sortEl){const v=sortEl.dataset.sort;sortMode=(v==='champ'||v==='name')?v:parseInt(v,10);render();return;}
  const cell=e.target.closest('[data-cell]');if(cell){const parts=cell.dataset.cell.split(':');openPanel(raceBrief(parts[0],parts[1]),DRV[parts[1]].team);return;}
  const drv=e.target.closest('[data-driver]');if(drv){openPanel(seasonBrief(drv.dataset.driver),DRV[drv.dataset.driver].team);return;}
  if(e.target.closest('.x')){closePanel();return;}
  const seg=e.target.closest('.seg button');if(seg){document.querySelectorAll('.seg button').forEach(b=>b.setAttribute('aria-selected','false'));seg.setAttribute('aria-selected','true');const drivers=seg.dataset.view==='drivers';const mw=document.getElementById('matrixWrap'),ww=document.getElementById('wccWrap');if(mw)mw.classList.toggle('hidden',!drivers);if(ww)ww.classList.toggle('hidden',drivers);document.getElementById('legend').classList.toggle('off',!drivers);}
});
scrim.addEventListener('click',closePanel);
document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanel();});

load();
